baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'We learn slovene 🇸🇮'
theme = 'relearn'


[params]
  collapsibleMenu = true

[module]
  [[module.imports]]
    path = 'github.com/hugomods/images'
    disable = true

[security]
  enableInlineShortcodes = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
